spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cursobackendjava?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
